# Generated by Django 5.0.7 on 2024-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='web-dev-1.jpg', upload_to='assets/media/blog_images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='Blog_Post', max_length=30),
        ),
    ]
