# Generated by Django 5.0.7 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_blogpost_image_alter_blogpost_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(max_length=30),
        ),
    ]
